image: registry.117sport.com/nodejs/node-ci:latest

cache:
  paths:
    - node_modules/

stages:
  - init
  - test

init:
  stage: init
  script:
    - npm install yarn -g --registry=https://registry.npm.taobao.org/
    - yarn --prod=false

test:
  stage: test
  script:
    - npm run test
