before_script:
  - export NVM_DIR="$HOME/.nvm"
  - \. "$NVM_DIR/nvm.sh"
  - nvm install stable
  - nvm use stable

cache:
  paths:
    - node_modules/

stages:
  - init
  - test

init:
  stage: init
  script:
    - echo '@bee:registry=https://npm.117sport.com' >> ~/.npmrc
    - echo '//npm.117sport.com/:_authToken="HcOBVSAkk5USRKngf/UtFw=="' >> ~/.npmrc
    - npm install yarn -g --registry=https://registry.npm.taobao.org/
    - yarn --prod=false

test:
  stage: test
  script:
    - npm run test
